require 'rake' 
require 'rake/testtask'

Rake::TestTask.new("spec:integration") do |t|
  t.libs = %w|lib spec|
  t.verbose = true 
  t.test_files = FileList['specs/integration/*_spec.rb']
end

Rake::TestTask.new("spec:unit") do |t|
  t.libs = %w|lib spec|
  t.verbose = true 
  t.test_files = FileList['specs/unit/*_spec.rb']
end

Rake::TestTask.new("spec:all") do |t|
  t.libs = %w|lib spec|
  t.verbose = true
  t.test_files = FileList['specs/**/*_spec.rb']
end

